### ISSUE TITLE
Custom sessions fields are not saved

### ISSUE THREAD

**Issue by basic70** [hendrysadrak/firestore-store#10]
I'm using express-session 1.16.2, with firestore-2.0, firebase-admin 8.2.0 and passport 0.4.0.
I initialize it like this:

    app.use(session({
        secret: 'very secret',
        resave: true,
        rolling: true,
        saveUninitialized: true,
        store: new FirestoreStore({ database: require(path.join(__dirname, 'modules', 'firestore'))})
    }))
    app.use(passport.initialize());
    app.use(passport.session());

This gives me a persisted session object like this, so the logged in user is kept when node is restarted. Below is a typical output from console.log('current session:', req.session).

current session: Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  passport: { user: '... a firestore id ...' } }

But then I want to save some more data, and have a post() handler where I set req.session.my_field = value;

However, in the firestore database, this field does not appear. Therefore, it can't be restored for the new request. With the default MemoryStore this works fine, but then the logged in user is of course cleared on restarts.

Is there something more I need to do to get the other fields in req.session to also be persisted?

**Comment by hendrysadrak** [comment]
maybe this helps https://www.npmjs.com/package/express-session#sessionsavecallback

**Comment by basic70** [comment]
> maybe this helps https://www.npmjs.com/package/express-session#sessionsavecallback

Thanks, but isn't that something that should be done by firestore-store already?

**Comment by hendrysadrak** [comment]
Nope, this is just a backend for express-session library, meant only as a connection to the data store (being firerbase) implemented by spec https://www.npmjs.com/package/express-session#session-store-implementation 

All the when what happens is done by express-session
