### ISSUE TITLE
Compatible with @google-cloud/firestore?

### ISSUE THREAD

**Issue by marshmellow1328** [hendrysadrak/firestore-store#6]
Is this compatible with @google-cloud/firestore?

**Comment by marshmellow1328** [comment]
Some early experimentation suggests it works. Using @google-cloud/firestore at v0.19.0.

```javascript
const session = require('express-session');
const Firestore = require('@google-cloud/firestore');
const FirestoreStore = require('firestore-store')(session);
const firestore = new Firestore();
const store = new FirestoreStore( { database: firestore } );
```

**Comment by hendrysadrak** [comment]
Yes it is. I can write tests for it.

**Comment by hendrysadrak** [comment]
@marshmellow1328 https://github.com/hendrysadrak/firestore-store/blob/master/examples/with-only-firestore.js there is a example for that use-case as well

**Comment by akeranen** [comment]
When @google-cloud/firestore is used there's no longer need for the firebase-admin dependency
