### ISSUE TITLE
I am struck at firebase-admin@5.13.1 dependency. 

### ISSUE THREAD

**Issue by Ayushtwentysix** [hendrysadrak/firestore-store#7]
I think there is some dependency in _firestore-store_ that is not allowing me to update _firebase-admin_ dependency in my project. So I am struck at firebase-admin@5.13.1. Please update all dependencies in _firestore-store_ to latest. Thanks 👍

**Comment by hendrysadrak** [comment]
Hey man. This module doesn't have any dependencies (as you can see from here https://www.npmjs.com/package/firestore-store?activeTab=dependencies). It only defines dev dependencies for running tests. 
Try deleting your package-lock and node_modules folder and doing `npm i && npm update`

**Comment by Ayushtwentysix** [comment]
Hey, thanks for helping me out. Now everything looks good.  😊
