### ISSUE TITLE
Session lookup does not work in Cloud Functions when running behind Firebase Hosting

### ISSUE THREAD

**Issue by kariem** [hendrysadrak/firestore-store#8]
I had some issues using this in Cloud Functions for Firebase, i.e. running Cloud Functions behind Firebase Hosting and think this should be documented.

See https://firebase.google.com/docs/hosting/manage-cache#using_cookies

The `name` should be set to `__session` in order for the cookie to be made available to the app.

**Comment by kariem** [comment]
Alternatively, we could also check runtime properties and add a warning, when the code is run in Cloud Functions but the name has not been overridden.

Please let me know, if this would be something that would made sense here.

**Comment by hendrysadrak** [comment]
> Alternatively, we could also check runtime properties and add a warning, when the code is run in Cloud Functions but the name has not been overridden.

Sure! Would be nice to allow disabling the warning with env variable.

**Comment by kariem** [comment]
Sorry for the late response here. I currently to not have much time, but I will try to do this as soon as I can.

**Comment by evdama** [comment]
I saw in the docs that using `__session` is the recommended way to deal with this. Is this still true and can the issue therefore be closed?

**Comment by hendrysadrak** [comment]
> When using Firebase Hosting together with Cloud Functions or Cloud Run, cookies are generally stripped from incoming requests. This is necessary to allow for efficient CDN cache behavior. **Only the specially-named __session cookie is permitted to pass through to the execution of your app**.

> When present, the __session cookie is automatically made a part of the cache key, meaning that it's impossible for two users with different cookies to receive the other's cached response. Only use the __session cookie if your app serves different content depending on user authorization.

Still true. Will close
